name: client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  msh_checkbox: ^2.0.1
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  collection: ^1.17.2
  cloud_functions: ^4.7.4
  synchronized: ^3.1.0
  firebase_messaging: ^14.9.2
  stream_d: ^0.3.0
  agora_rtc_engine: ^6.2.4
  agora_uikit: ^1.3.7
  sliding_up_panel: ^2.0.0+1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/RedHatDisplay/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Light.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-LightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Light.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Italic.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Medium.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-SemiBold.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-ExtraBold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          weight: 800
          style: italic
